###########################################################################
# WTC ChAMP/limma PTSD analysis Lasso 
###########################################################################

# Limma analysis variables: Age, Smoking, PTSD_status2

###########################################################################
# Step 1: Run limma analysis
###########################################################################

library(limma)
library(ChAMP)

load("WTC224_ChAMP_GenomeStudio_LASSO_prep.Rdata")
pheno<-read.csv("/ifs/data/msph/epi/WTC/input/WTC224_pheno_TRF_minfi_blood_counts.csv", row.names=1)
data<-beta.norm
rm(beta.norm)

rownames(pheno)
colnames(data)

match(colnames(data), rownames(pheno))

pheno<-pheno[colnames(data), ]

match(colnames(data), rownames(pheno))


# Age, Smoking, PTSD_status2, and CellCounts as covars

design.PTSD<-model.matrix(~age_interview+smoking+factor(d_race8)+CD8T+CD4T+NK+Bcell+Mono+PTSD_status2, data=pheno)
colnames(design.PTSD)
colnames(design.PTSD)[match("factor(d_race8)3", colnames(design.PTSD))]<-"race_3"
colnames(design.PTSD)[match("factor(d_race8)4", colnames(design.PTSD))]<-"race_4"
colnames(design.PTSD)[match("factor(d_race8)5", colnames(design.PTSD))]<-"race_5"
colnames(design.PTSD)[match("factor(d_race8)7", colnames(design.PTSD))]<-"race_7"
colnames(design.PTSD)[match("factor(d_race8)8", colnames(design.PTSD))]<-"race_8"
colnames(design.PTSD)

fit.PTSD <- lmFit(data, design.PTSD)

sum(is.na(fit.PTSD$coefficients)==TRUE)
head(fit.PTSD$coefficients)

contrast.matrix.PTSD<-makeContrasts(PTSD_status2, levels=design.PTSD)
rownames(contrast.matrix.PTSD)[1]<-"(Intercept)" # have to rename the contrast matrix
contrast.matrix.PTSD
fit2.PTSD<-contrasts.fit(fit.PTSD, contrast.matrix.PTSD)
fit2.PTSD<-eBayes(fit2.PTSD)

topResults.PTSD<-topTable(fit2.PTSD,number=20,coef=1, adjust="BH")
topResults.PTSD

# Note: the easiest way to run the lasso for differentially methylated regions 
# that are not significant after FDR correction is to rename the
# limma object's columns and have the unadjusted p-value be "adj.P.val"
# and then set the adjPval to be 10^-3 

limma.test<-topTable(fit2.PTSD,number=nrow(fit.PTSD),coef=1, adjust="BH")

colnames(mvp) # mvp was generated by champ.mvp
colnames(topResults.PTSD) 

# it looks like the champ.mvp output is the limma output + probe.features +
# the averages for the two groups that are compared + the differences between
# the two groups beta values.

# we need averages and difference (X0_AVG, X1_AVG, deltaBeta)
# to run champ.lasso (tmp4), but how to do? Put in PTSD never vs any avgs

###########################################################################
# Step 2: Merge champ.MVP with limma analysis
###########################################################################

data(probe.features)
limma.test.merge<-merge(limma.test, probe.features, by="row.names")
rownames(limma.test.merge)<-limma.test.merge[, "Row.names"]
limma.test.merge<-limma.test.merge[, -1]

# Need to add "probeID" for the lasso code to work
limma.test.merge$probeID<-NA
limma.test.merge$probeID<-rownames(limma.test.merge)

# add in averages and deltaBeta
limma.avgs<-mvp[, 28:30] # difference bewten Never/Amny no covars from champ.mvp

limma.test.merge<-merge(limma.test.merge, limma.avgs, by="row.names")
limma.test.merge<-limma.test.merge[, colnames(mvp)]
rownames(limma.test.merge)<-limma.test.merge[, "probeID"]
limma<-limma.test.merge
colnames(limma)

rm(limma.test.merge,limma.avgs, limma.test, probe.features)


###########################################################################
# Step 3: Run LASSO
###########################################################################

# convert unadjusted p-value "adj.P.Val" for probe lasso analysis
colnames(limma)
colnames(mvp)
limma<-limma[, colnames(mvp)]
colnames(limma)[match("adj.P.Val", colnames(limma))]<-c("original_FDR_Pval")
colnames(limma)[match("P.Value", colnames(limma))]<-c("adj.P.Val")

lasso<-champ.lasso(fromFile=TRUE, uploadResults=FALSE, limma=limma, 
                   beta.norm = data, pd = myLoad.pd, filterXY = TRUE, image = TRUE, mafPol.lower = 0, 
                   mafPol.upper = 0.05, popPol = "eur", lassoStyle = "max", lassoRadius = 2000, 
                   minSigProbesLasso = 2, minDmrSep = 1000, minDmrSize = 0, adjPVal = 0.001, 
                   adjust.method = "BH", resultsDir = paste(getwd(), "resultsChamp", sep = "/"), 
                   bedFile = TRUE, DMRpval = 0.05, batchDone = FALSE)

save(limma, lasso, file=paste("WTC", ncol(data), "_GenomeStudio_MINFI_lasso_AgeSmokeRaceCellCountsPTSD_minSig2.Rdata", sep=""))
write.csv(lasso, paste("WTC", ncol(data), "_GenomeStudio_MINFI_lasso_AgeSmokeRaceCellCountsPTSD_minSig2_LASSO.csv", sep=""))
